INSERT INTO TODO (ID, DESCRIPTION, DONE, TARGET_DATE, USERNAME) VALUES (101, 'Learn Angular', false, CURRENT_DATE(), 'admin');
INSERT INTO TODO (ID, DESCRIPTION, DONE, TARGET_DATE, USERNAME) VALUES (102, 'Learn MongoDB', false, CURRENT_DATE(), 'admin');
INSERT INTO TODO (ID, DESCRIPTION, DONE, TARGET_DATE, USERNAME) VALUES (103, 'Improve Python skills', false, CURRENT_DATE(), 'admin');